### ISSUE TITLE
I cannot understand a  part of the code.  is it a bug or I misunderstand it?

### ISSUE THREAD

**Issue by springluo** [neurosim/DNN_NeuroSim_V2.0#2]
In the file  **quantization_cpu_np_infer.py**  line **113-114**:
```python  
outputPartial= F.conv2d(input, remainderQ*mask, self.bias, self.stride, self.padding, self.dilation, self.groups)
outputDummyPartial= F.conv2d(input, dummyP*mask, self.bias, self.stride, self.padding, self.dilation, self.groups)
```

why  the input of `F.conv2d` is `input`, not `inputB` in line 98. Similar  problem in line  256-257,290-291.

but in line 148-149. the input of `F.conv2d` is `inputB`
```python
outputPartial= F.conv2d(inputB, remainderQ*mask, self.bias, self.stride, self.padding, self.dilation, self.groups)
outputDummyPartial= F.conv2d(inputB, dummyP*mask, self.bias, self.stride, self.padding, self.dilation, self.groups)

```
I think the input of `conv2d` in line 113-114,256-257,290-291 should  be inputed bit by bit ,so the input of `conv2d` should also  be the variable `inputB` .

did I misunderstand that or it  is just a bug? 
can you explain it? Thank you .

**Comment by neurosim** [comment]
Hi, you are correct, we have updated the code accordingly.
