### ISSUE TITLE
Inference failed

### ISSUE THREAD

**Issue by jerryzj** [neurosim/DNN_NeuroSim_V2.0#5]
Hi,
When I run the inference code (After training), the terminal report the following

```bash
Traceback (most recent call last):
  File "inference.py", line 99, in <module>
    hook_handle_list = hook.hardware_evaluation(modelCF,args.wl_weight,args.wl_activate)
TypeError: hardware_evaluation() missing 1 required positional argument: 'numEpoch'
```

Please fix it, thanks

**Comment by neurosim** [comment]
Hi, thanks for the report, we have updated the hardware_evaluation function, so the number of arguments is four, we have update the codes accordingly.
`hook_handle_list = hook.hardware_evaluation(modelCF,args.wl_weight,args.wl_activate,0)`
